### PR TITLE
Don't hex encode vFile count responses

### PR DESCRIPTION
**Pull request by fjricci**

### CODE REVIEW

**Comment by sas** [comment]
@facebook-github-bot shipit

How did this work before?

**Comment by fjricci** [comment]
Well, this packet wasn't being used at all until I implemented the underlying vFile stuff. I was just dumb and assumed that the response part was correct 😆

**Comment by fjricci** [comment]
(As in, the response stuff was existing code that I didn't verify until now)

**Comment by fjricci** [comment]
Turns out that lldb uses decimal but gdb uses hex. Because why not.

**Comment by a20012251** [comment]
@facebook-github-bot shipit

**Comment by fjricci** [comment]
Fixed nit on variable name and committed as a447204262690658380b90f1782383337d4aa4f9

**Pull request closed without merging**
