### PR TITLE
Add the clang-only flag -Wshorten-64-to-32

### PR DESCRIPTION
**Pull request by a20012251**
I mainly used these two replacement commands because I trust the compiler more than myself

for: X = Y;
.s/\( *\)\(.*\) = \(.*\);/\1\2 = static_cast<typeof(\2)>(\3);

for: type X = Y;
.s/\( *\)\(.*\) \(.*\) = \(.*\);/\1\2 \3 = static_cast<\2>(\4);

very few cases required an explicit type

### CODE REVIEW

**Comment by kastiglione** [comment]
Are there cases where this warning will come in handy? It seems like the change adds the warning and then silences it with casts throughout.

**Comment by a20012251** [comment]
Well, my intention right now is not to fix any possible bug. However, this
flag will make new code mindful of casting, hopefully preventing bugs.

2016-03-11 9:10 GMT-08:00 Dave Lee <notifications@github.com>:

> Are there cases where this warning will come in handy? It seems like the
> change adds the warning and then silences it with casts throughout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/pull/216#issuecomment-195458985>.
>



-- 
Walter Erquínigo Pezo

Every problem has a simple, fast and wrong solution.

**Comment by a20012251** [comment]
well, i'll verify each cast

**Comment by sas** [comment]
Should we close this and get rid of the branch?

**Pull request closed without merging**
