### PR TITLE
Windows continue and single step.

### PR DESCRIPTION
**Pull request by sas**
With this, we can single-step through the execution of a process, and get assembly output.

```
(lldb) si
Process 37584 resuming
Process 37584 stopped
* thread #1: tid = 0x7ccc, 0x77500884, name = '<NONE>', stop reason = signal SIGTRAP
    frame #0: 0x77500884
-> 0x77500884: movl   %ebx, 0x8(%esp)
   0x77500888: jmp    0x7751accf
   0x7750088d: leal   (%ecx), %ecx
   0x77500890: movl   %esp, %edx
(lldb)
```

### CODE REVIEW

**Comment by strager** [comment]
What's memory read/write used for?

**Comment by sas** [comment]
Used for the debugger to play with variables. Also, used to read the memory
around eip so we can display a disassembly of what we're executing right
now (if source-level debugging is not available).

On Wed, Jun 17, 2015 at 1:23 PM, strager <notifications@github.com> wrote:

> What's memory read/write used for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/pull/32#issuecomment-112938803>.
>



-- 
Stephane Sezer

**Comment by strager** [comment]
lgtm except missing `CloseHandle` calls.

**Comment by sas** [comment]
Thanks for the review.

On Wed, Jun 17, 2015 at 1:26 PM, strager <notifications@github.com> wrote:

> lgtm except missing CloseHandle calls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/pull/32#issuecomment-112939575>.
>



-- 
Stephane Sezer

**Pull request merged**
