### PR TITLE
Fix definition of the x87 ftag register

### PR DESCRIPTION
**Pull request by xiaobai**
This was recently fixed in LLDB (by @compnerd) in https://reviews.llvm.org/rL311579.

This should fix things in ds2.

### CODE REVIEW

**Comment by xiaobai** [comment]
I don't think this change can go in until we switch over to LLDB 5.0, as this will break a decent amount of LLDB 4.0 tests.

**Comment by fjricci** [comment]
Will it break just the register-reading tests or will it also break other behavior?

**Comment by xiaobai** [comment]
I've been using this patch locally and it hasn't broken any behavior for me yet. It will probably just break the register reading tests.

**Comment by fjricci** [comment]
Depending how many fail, you could add patch files.

**Comment by sas** [comment]
Let's close the loop on this one. Should we add blacklists for register tests or should we just switch to using 5.0 for testing?

**Comment by xiaobai** [comment]
I think we should switch to 5.0 for testing. The branch cut was ~1 month ago and it seems rather stable.

**Pull request merged**
