### PR TITLE
Bump minimum CMake version.

### PR DESCRIPTION
**Pull request by sas**

### CODE REVIEW

**Comment by fjricci** [comment]
@facebook-github-bot shipit

**Comment by kokarez** [comment]
What is the need here ?

**Comment by sas** [comment]
The generators used in `target_compile_options` have been added in cmake
3.3. If you try to configure this with 3.2, you get errors like

```
CMake Error at Tools/JSObjects/CMakeLists.txt:51 (target_compile_options):
Error evaluating generator expression: $<COMPILE_LANGUAGE:C> Expression did
not evaluate to a known generator expression
```

On Wed, May 18, 2016 at 11:19 AM, kokarez <notifications@github.com> wrote:

> What is the need here ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/pull/345#issuecomment-220114057>
>



-- 
Stephane Sezer

**Comment by kokarez** [comment]
:+1:

**Pull request merged**
