### PR TITLE
Make sure to clear register info even when unset

### PR DESCRIPTION
**Pull request by fjricci**

### CODE REVIEW

**Comment by sas** [comment]
@facebook-github-bot shipit

**Comment by sas** [comment]
Does that allow us to re-enable more tests?

**Comment by fjricci** [comment]
Nope, there's still another bug in the numbering system, haven't decided if it's ds2 or lldb yet.

**Comment by sas** [comment]
Committed as 36a879c0dcd5b485f65fdcee2e5820090130ecba.

**Pull request closed without merging**
