### PR TITLE
Add Appveyor 

### PR DESCRIPTION
**Pull request by a20012251**

### CODE REVIEW

**Comment by sas** [comment]
The toolchain file is empty and the comment in there is not relevant for Windows (only WinPhone).

**Comment by a20012251** [comment]
It works without the file, so I removed that trash.

**Comment by sas** [comment]
@facebook-github-bot shipit

**Comment by a20012251** [comment]
commited as 3ea38519c5a7ca0b4dbd14cd9bcabcc808941daf

**Pull request closed without merging**
