### PR TITLE
Enable Concurrent testing

### PR DESCRIPTION
**Pull request by fjricci**
Depends on enable/disable PR, but putting up separately in case there are other issues.

### CODE REVIEW

**Comment by xiaobai** [comment]
Looks like there's some overlap with #523?

**Comment by fjricci** [comment]
Yes, intentionally so (see comment)

**Comment by xiaobai** [comment]
Ah I see, didn't know what you meant by "Depends on enable/disable PR". Thanks for clarifying.

**Comment by fjricci** [comment]
Yeah, I was going to link the PR number but I was lazy 😆

**Comment by fjricci** [comment]
rebase --ignore-date doesn't seem to have totally worked here, some of the commits from https://github.com/facebook/ds2/pull/523 are not in order with respect to the ESRCH commits. Should be resolved once that PR goes in though.

**Comment by xiaobai** [comment]
Yeah, github shows commits in linear order based on commit time. It definitely commits them in the correct order though.

**Comment by fjricci** [comment]
Damn circleci isn't fooled by close-open

**Comment by lanza** [comment]
Rebased and updated in https://github.com/facebook/ds2/pull/644

**Pull request closed without merging**
