### PR TITLE
Re-enable register commands lldb unit test

### PR DESCRIPTION
**Pull request by fjricci**

### CODE REVIEW

**Comment by sas** [comment]
@facebook-github-bot shipit

**Comment by sas** [comment]
When did these start passing?

**Comment by fjricci** [comment]
Not sure, but I took 4 random Travis builds to see what XPASSed and was disabled by us and not lldb. This was the only one.

**Comment by sas** [comment]
Cool.

On Friday, April 15, 2016, Francis Ricci <notifications@github.com> wrote:

> Not sure, but I took 4 random Travis builds to see what XPASSed and was
> disabled by us and not lldb. This was the only one.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/pull/281#issuecomment-210487043>
>


-- 
Stephane Sezer

**Pull request merged**
