### PR TITLE
Prevent ds2 from hanging after process termination

### PR DESCRIPTION
**Pull request by fjricci**

### CODE REVIEW

**Comment by sas** [comment]
This looks interesting but let's sit together tomorrow to go over it.

**Comment by sas** [comment]
BTW, while we figure out how to properly wait on a child on Linux, you can submit the first patch (remove `hang` argument).

**Comment by sas** [comment]
@facebook-github-bot shipit

**Comment by fjricci** [comment]
Committed as 428f8acc4a7113dcf105fcbe1915f9d3a6606844...05b29a476aed923353a1d60fb487442e2080fbe0

**Pull request closed without merging**
